# Generated by Django 5.0.6 on 2024-06-29 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hired_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 29, 22, 51, 19, 57991)),
        ),
    ]
